### ISSUE TITLE
刷题plugin推荐

### ISSUE THREAD

**Issue by hhhwwwuuu** [bigchange/go-practice#5]
Bro，看你在刷leetcode。
推荐你个插件，可以直接在jetbrain里使用。挺爽的
https://github.com/shuzijun/leetcode-editor

**Comment by shanghai-Jerry** [comment]
> Bro，看你在刷leetcode。
> 推荐你个插件，可以直接在jetbrain里使用。挺爽的
> https://github.com/shuzijun/leetcode-editor

多谢
